version: '3'

services:
  db:
    image: mongo
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_week:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


